name: Build

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install dependencies
        run: sudo apt-get -y install latexmk make texlive texlive-fonts-extra texlive-xetex
      - name: Run LaTeX
        run: make
      - name: Upload PDF as artifact
        uses: actions/upload-artifact@v3
        with:
          name: cv
          path: cv.pdf
